CREATE DATABASE LibraryDb;
GO
USE LibraryDb;
GO
CREATE TABLE Work (
    Code INT IDENTITY
   ,Title NVARCHAR(50) COLLATE French_CI_AS NOT NULL
   ,[State] BIT NOT NULL CONSTRAINT DF_Work_State DEFAULT (1)
   ,BorrowCount INT NOT NULL CONSTRAINT DF_Work_BorrowCount DEFAULT (0)
   ,CONSTRAINT PK_Work PRIMARY KEY CLUSTERED (Code)
) ON [PRIMARY]
GO
CREATE TABLE Book (
    Code INT NOT NULL
   ,AuthorName NVARCHAR(50) COLLATE French_CI_AS NOT NULL
   ,EditorName NVARCHAR(50) COLLATE French_CI_AS NOT NULL
   ,CONSTRAINT PK_Book PRIMARY KEY CLUSTERED (Code)
   ,CONSTRAINT FK_Book_Work FOREIGN KEY (Code) REFERENCES dbo.Work (Code) ON DELETE CASCADE ON UPDATE CASCADE
) ON [PRIMARY]
GO
CREATE TABLE CD (
    Code INT NOT NULL
   ,ArtistName NVARCHAR(50) COLLATE French_CI_AS NOT NULL
   ,TrackCount INT NOT NULL CONSTRAINT DF_CD_TrackCount DEFAULT (0)
   ,CONSTRAINT PK_CD PRIMARY KEY CLUSTERED (Code)
   ,CONSTRAINT FK_CD_Work FOREIGN KEY (Code) REFERENCES dbo.Work (Code) ON DELETE CASCADE ON UPDATE CASCADE
) ON [PRIMARY]
GO